### ISSUE TITLE
Issue: republishes don't show in google analytics

### ISSUE THREAD

**Issue by eecoston** [Automattic/republication-tracker-tool#101]
For some reason analytics from the tracking pixel using the republishing tool are not showing up in google analytics. The only way is to happen to check the edit post screen for that post and see the list at the bottom.[https://calmatters.network/wp-admin/post.php?post=51876&action=edit]( https://calmatters.network/wp-admin/post.php?post=51876&action=edit)

**Comment by adekbadek** [comment]
Hi, the tracking data is saved both in post meta and in GA - but only if a [GA tracking ID is provided](https://github.com/Automattic/republication-tracker-tool/blob/master/docs/configuring-plugin-settings.md#republication-tracker-tool-google-analytics-id).

You can then view the data in GA by visiting the Acquisition -> All Traffic -> Referrals view. There you should set the secondary dimension to "App Name":

![image](https://user-images.githubusercontent.com/7383192/115543905-3440dd80-a2a2-11eb-82bb-fcb22ca1e56b.png)

And apply an advanced filter - "App Name" matching "Republication":

![image](https://user-images.githubusercontent.com/7383192/115544016-5dfa0480-a2a2-11eb-9d7a-a459400e5acf.png)

**Comment by eecoston** [comment]
Thanks. Turns out I just had to change from GA4 to the old UA tags to get this to work
