### ISSUE TITLE
How to see all republications in GA4?

### ISSUE THREAD

**Issue by johm** [Automattic/republication-tracker-tool#189]
I see that the UA version of the tracking pixel would set an "Application Name" as a parameter to make it easy to see all page views from republications. What's the equivalent for GA4?

**Comment by dkoo** [comment]
@johm we just opened #190 which will add several custom `shared_post_*`GA4 parameters so you will be able to create Exploration reports around them. This PR also updates the GA4 documentation to provide basic examples of how to create custom reports in GA4 to view `page_view` data. In the meantime, if you know what referring domains to look for, you can create reports using the `Page referrer` dimensions and isolate them to the referring domains to view this data.
