### ISSUE TITLE
Provide options for what to include in byline

### ISSUE THREAD

**Issue by benlk** [Automattic/republication-tracker-tool#46]
- [ ] the author name
- [ ] the site title

**Comment by benlk** [comment]
- [ ] generally, use the byline functions to populate the credit instead of the literal `post_author` https://github.com/INN/republication-tracker-tool/blob/4775fa7d7f63456c82b6e5ecff36ab07f4bfd05f/includes/shareable-content.php#L106
    - this adds Co-Authors Plus compatibility

**Comment by tmmbecker** [comment]
We just had a Newspack publisher request this. Any chance we can add some priority to this one? We have several that use the republication tracker with CAP and they'd love to see the post author in the byline shared here rather than the person assigned as the WordPress author.

**Comment by benlk** [comment]
There is a PR adding this functionality in https://github.com/Automattic/republication-tracker-tool/pull/87
