### ISSUE TITLE
Add the bin/ directory to the list of files to be excluded when packaging up this plugin

### ISSUE THREAD

**Issue by benlk** [Automattic/republication-tracker-tool#85]
https://github.com/INN/republication-tracker-tool/blob/4775fa7d7f63456c82b6e5ecff36ab07f4bfd05f/release.sh#L10

There's no need for us to be shipping a shell script that installs tests as part of the plugin.

**Comment by adekbadek** [comment]
There's a different release mechanism in place now, and it does not ship any unneeded files.
